# This file configures the analyzer
# `flutter analyze`

# recommanded lints
include: package:flutter_lints/flutter.yaml

linter:
  # Add or remove Lints for howl project here
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Disable for one code line or file:
  # `// ignore: name_of_lint`
  # `// ignore_for_file: name_of_lint`
  rules:
    # remove them before release
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false
